In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('listings_mexico.csv')

In [5]:
df.describe()

,id,scrape_id,host_id,host_listings_count,host_total_listings_count,neighbourhood_group_cleansed,latitude,longitude,accommodates,bathrooms,...,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,license,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
count,2.606700e+04,2.606700e+04,2.606700e+04,26062.000000,26062.000000,0.0,26067.000000,26067.000000,26067.000000,22062.000000,...,22805.000000,22805.000000,22805.000000,22805.000000,0.0,26067.000000,26067.000000,26067.000000,26067.000000,22806.000000
mean,6.041349e+17,2.025032e+13,2.288527e+08,25.900852,35.072826,NaN,19.405242,-99.166046,3.346760,1.451432,...,4.837276,4.823005,4.840322,4.713932,NaN,15.491886,12.622626,2.690068,0.141904,1.803389
std,5.265872e+17,7.906402e+00,1.954205e+08,86.765206,123.984298,NaN,0.042514,0.033489,2.359036,1.030367,...,0.326791,0.360575,0.298210,0.394899,NaN,36.230505,35.795452,7.340992,1.566747,2.032845
min,3.579700e+04,2.025032e+13,7.365000e+03,1.000000,1.000000,NaN,19.095762,-99.339630,1.000000,0.000000,...,1.000000,1.000000,1.000000,1.000000,NaN,1.000000,0.000000,0.000000,0.000000,0.010000
25%,4.164114e+07,2.025032e+13,5.259008e+07,1.000000,2.000000,NaN,19.391840,-99.178873,2.000000,1.000000,...,4.820000,4.800000,4.800000,4.670000,NaN,1.000000,0.000000,0.000000,0.000000,0.450000
50%,7.398440e+17,2.025032e+13,1.648988e+08,4.000000,5.000000,NaN,19.415150,-99.167399,2.000000,1.000000,...,4.920000,4.920000,4.920000,4.800000,NaN,3.000000,1.000000,0.000000,0.000000,1.230000
75%,1.090846e+18,2.025032e+13,3.991943e+08,14.000000,17.000000,NaN,19.431940,-99.154379,4.000000,2.000000,...,5.000000,5.000000,5.000000,4.910000,NaN,11.000000,6.000000,2.000000,0.000000,2.560000
max,1.379814e+18,2.025032e+13,6.847160e+08,886.000000,1049.000000,NaN,19.561010,-98.963360,16.000000,49.000000,...,5.000000,5.000000,5.000000,5.000000,NaN,242.000000,242.000000,65.000000,28.000000,61.050000

In [6]:
len(df)

26067

In [7]:
df.head()

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,35797,https://www.airbnb.com/rooms/35797,20250319150644,2025-03-21,city scrape,Villa Dante,"Dentro de Villa un estudio de arte con futon, ...","Santa Fe Shopping Mall, Interlomas Park and th...",https://a0.muscache.com/pictures/f395ab78-1185...,153786,...,NaN,NaN,NaN,NaN,f,1,1,0,0,NaN
1,44616,https://www.airbnb.com/rooms/44616,20250319150644,2025-03-20,previous scrape,Condesa Haus,A new concept of hosting in mexico through a b...,NaN,https://a0.muscache.com/pictures/251410/ec75fe...,196253,...,4.78,4.98,4.47,NaN,f,9,4,2,0,0.40
2,56074,https://www.airbnb.com/rooms/56074,20250319150644,2025-03-20,city scrape,Great space in historical San Rafael,This great apartment is located in one of the ...,Very traditional neighborhood with all service...,https://a0.muscache.com/pictures/3005118/60dac...,265650,...,4.94,4.76,4.79,NaN,f,1,1,0,0,0.49
3,67703,https://www.airbnb.com/rooms/67703,20250319150644,2025-03-20,previous scrape,"2 bedroom apt. deco bldg, Condesa","Comfortably furnished, sunny, 2 bedroom apt., ...",NaN,https://a0.muscache.com/pictures/3281720/6f078...,334451,...,4.92,4.98,4.92,NaN,f,2,2,0,0,0.31
4,70644,https://www.airbnb.com/rooms/70644,20250319150644,2025-03-22,city scrape,Beautiful light Studio Coyoacan- full equipped !,COYOACAN designer studio quiet & safe! well eq...,Coyoacan is a beautiful neighborhood famous fo...,https://a0.muscache.com/pictures/f397d2da-d045...,212109,...,4.98,4.96,4.92,NaN,f,3,2,1,0,0.83

In [8]:
df

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,35797,https://www.airbnb.com/rooms/35797,20250319150644,2025-03-21,city scrape,Villa Dante,"Dentro de Villa un estudio de arte con futon, ...","Santa Fe Shopping Mall, Interlomas Park and th...",https://a0.muscache.com/pictures/f395ab78-1185...,153786,...,NaN,NaN,NaN,NaN,f,1,1,0,0,NaN
1,44616,https://www.airbnb.com/rooms/44616,20250319150644,2025-03-20,previous scrape,Condesa Haus,A new concept of hosting in mexico through a b...,NaN,https://a0.muscache.com/pictures/251410/ec75fe...,196253,...,4.78,4.98,4.47,NaN,f,9,4,2,0,0.40
2,56074,https://www.airbnb.com/rooms/56074,20250319150644,2025-03-20,city scrape,Great space in historical San Rafael,This great apartment is located in one of the ...,Very traditional neighborhood with all service...,https://a0.muscache.com/pictures/3005118/60dac...,265650,...,4.94,4.76,4.79,NaN,f,1,1,0,0,0.49
3,67703,https://www.airbnb.com/rooms/67703,20250319150644,2025-03-20,previous scrape,"2 bedroom apt. deco bldg, Condesa","Comfortably furnished, sunny, 2 bedroom apt., ...",NaN,https://a0.muscache.com/pictures/3281720/6f078...,334451,...,4.92,4.98,4.92,NaN,f,2,2,0,0,0.31
4,70644,https://www.airbnb.com/rooms/70644,20250319150644,2025-03-22,city scrape,Beautiful light Studio Coyoacan- full equipped !,COYOACAN designer studio quiet & safe! well eq...,Coyoacan is a beautiful neighborhood famous fo...,https://a0.muscache.com/pictures/f397d2da-d045...,212109,...,4.98,4.96,4.92,NaN,f,3,2,1,0,0.83
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26062,1379327529227113949,https://www.airbnb.com/rooms/1379327529227113949,20250319150644,2025-03-22,city scrape,Cama en Dorm mixto de 4 personas,Casa Pepe is a hotel with a hostel vocation th...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,261044377,...,NaN,NaN,NaN,NaN,t,8,0,4,4,NaN
26063,1379338090263773362,https://www.airbnb.com/rooms/1379338090263773362,20250319150644,2025-03-20,city scrape,loft #307 excelente ubicaciÃ³n ideal para descanso,Very nice room for 2 people (children under 12...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,175442219,...,NaN,NaN,NaN,NaN,f,1,0,1,0,NaN
26064,1379781424660291699,https://www.airbnb.com/rooms/1379781424660291699,20250319150644,2025-03-20,city scrape,Cozy room in Roma Norte,Located in the Colonia Roma Norte (Roma-Condes...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,34664434,...,NaN,NaN,NaN,NaN,f,2,0,2,0,NaN
26065,1379807014531191212,https://www.airbnb.com/rooms/1379807014531191212,20250319150644,2025-03-22,city scrape,Stylish suite w private terrace close to Polanco,Tucked away in the lively neighborhood of Anzu...,Anzures is situated in the heart of Mexico Cit...,https://a0.muscache.com/pictures/prohost-api/H...,515054008,...,NaN,NaN,NaN,NaN,t,32,32,0,0,NaN
26066,1379814270520534429,https://www.airbnb.com/rooms/1379814270520534429,20250319150644,2025-03-20,city scrape,Depto. en el corazÃ³n de Roma N,"Apartment with 2 bedrooms, 2 bathrooms, 2 doub...",NaN,https://a0.muscache.com/pictures/miso/Hosting-...,189134785,...,NaN,NaN,NaN,NaN,f,1,1,0,0,NaN

In [9]:
df[['price']].isnull().sum()

price    3999
dtype: int64

In [10]:
df = df.dropna(subset=['price'])

In [11]:
df[['price']].isnull().sum()

price    0
dtype: int64

In [14]:
df = df.copy()  # Add this line before your operations
df['price'] = df['price'].str.replace('$', '')
df['price'] = df['price'].str.replace(',', '')
df['price'] = df['price'].astype(float)

AttributeError: Can only use .str accessor with string values!

In [11]:
df['price'].mean()

1665.005981511691

In [12]:
df['room_type'].value_counts()

room_type
Entire home/apt    14843
Private room        6995
Shared room          169
Hotel room            61
Name: count, dtype: int64

In [13]:
df['host_name'].value_counts()

host_name
Alejandra       305
Alejandro       244
Juan            241
Blueground      225
Raul            225
               ...
Elsa Eugenia      1
Jose P.           1
Juan Alberto      1
Neal              1
Kath              1
Name: count, Length: 3602, dtype: int64

In [14]:
df.columns

Index(['id', 'listing_url', 'scrape_id', 'last_scraped', 'source', 'name',
       'description', 'neighborhood_overview', 'picture_url', 'host_id',
       'host_url', 'host_name', 'host_since', 'host_location', 'host_about',
       'host_response_time', 'host_response_rate', 'host_acceptance_rate',
       'host_is_superhost', 'host_thumbnail_url', 'host_picture_url',
       'host_neighbourhood', 'host_listings_count',
       'host_total_listings_count', 'host_verifications',
       'host_has_profile_pic', 'host_identity_verified', 'neighbourhood',
       'neighbourhood_cleansed', 'neighbourhood_group_cleansed', 'latitude',
       'longitude', 'property_type', 'room_type', 'accommodates', 'bathrooms',
       'bathrooms_text', 'bedrooms', 'beds', 'amenities', 'price',
       'minimum_nights', 'maximum_nights', 'minimum_minimum_nights',
       'maximum_minimum_nights', 'minimum_maximum_nights',
       'maximum_maximum_nights', 'minimum_nights_avg_ntm',
       'maximum_nights_avg_ntm', 'calendar_updated', 'has_availability',
       'availability_30', 'availability_60', 'availability_90',
       'availability_365', 'calendar_last_scraped', 'number_of_reviews',
       'number_of_reviews_ltm', 'number_of_reviews_l30d', 'availability_eoy',
       'number_of_reviews_ly', 'estimated_occupancy_l365d',
       'estimated_revenue_l365d', 'first_review', 'last_review',
       'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'license', 'instant_bookable',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms', 'reviews_per_month'],
      dtype='object')

In [15]:
df['host_neighbourhood'].value_counts()

host_neighbourhood
Polanco                                        1487
Roma Norte                                     1002
Condesa                                         645
Chapultepec Morales                             605
Centro HistÃ³rico de la Ciudad de MÃ©xico         460
                                               ...
Tlatilco                                          1
Hell's Kitchen                                    1
reforma social                                    1
Xoco, Benito JuÃ¡rez - Muy cerca de CoyoacÃ¡n       1
Cerro Norte                                       1
Name: count, Length: 891, dtype: int64

In [16]:
df['host_id'].value_counts()

host_id
498701635    225
10764020     178
16148871     159
333035396    144
245618000    105
            ...
415363200      1
10038590       1
112249312      1
177880021      1
189134785      1
Name: count, Length: 9802, dtype: int64

In [17]:
df['host_name'].value_counts()

host_name
Alejandra       305
Alejandro       244
Juan            241
Blueground      225
Raul            225
               ...
Elsa Eugenia      1
Jose P.           1
Juan Alberto      1
Neal              1
Kath              1
Name: count, Length: 3602, dtype: int64

In [20]:
host_counts = df.groupby(['host_id', 'host_name']).size().sort_values(ascending=False)
print(host_counts)

host_id    host_name
498701635  Blueground            225
10764020   Mr. W                 178
16148871   Juan                  159
333035396  Clau                  144
245618000  Alejandra             105
                                ...
108892555  Magali Del Socorro      1
108732385  Patti                   1
108731535  Erick                   1
108631341  Charlotte               1
684715954  Dafne Daniela           1
Length: 9800, dtype: int64